name: Check

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Check
        run: npm run check

      - name: Smoke Test
        run: npm run test:smoke
